DROP TABLE CITY;

CREATE TABLE CITY(
   ID IDENTITY PRIMARY KEY,
   COUNTRY_CODE VARCHAR(10),
   CITY_NAME VARCHAR(1000),
   ACCENT_CITY VARCHAR(1000),
   REGION VARCHAR(100),
   POPULATION VARCHAR(100),
   LATITUDE VARCHAR(100),
   LONGITUDE VARCHAR(100)
);